### ISSUE TITLE
del pozo

### ISSUE THREAD

**Issue by nikitanipone** [primerproyecto/ahora-puedo-ver#1]
http://www.delpozo.com

**Comment by primerproyecto** [comment]
del pozo???. tu si que eres del pozo

**Comment by primerproyecto** [comment]
lo he pensado mejor y me vale

**Comment by nikitanipone** [comment]
Ahora puedo ver…

Una colección que habla sobre la importancia de la “mirada”. Entendiendo esta como  una serie  de ecuaciones matemáticas basadas en creencias aprendidas  y un intento de elaborar simetrías con lo que consideramos puede ser mas cercano a nuestra verdad.

NIKITA NIPONE plantea un ejercicio para olvidarse de esas creencias y volver al cuerpo. Disfrutar de la experiencia de sentir nuestras emociones y actuar sin elaborar pensamientos. Esto mismo intentó el movimiento artístico norteamericano conocido como “Expresionismo abstracto” , liberar la emoción y convertirla en pinceladas. La esencia de este movimiento acompaña la colección, llena de geometrías, colores  y diferentes texturas que se empastan.

Ahora puedo ver…Un viaje a través del cuerpo, de la mano de una maestra en este terreno, la bailarina y coreógrafa contemporánea CAMILLE HANSON, ella nos ha acompañado en este viaje, sintiendo cada prenda y dejándose llevar por lo que estas le transmitían.

Deseamos que lo disfrutéis
NIKITA NIPONE
