### ISSUE TITLE
Ancho máximo de imagenes del catalogo y sugerencia.

### ISSUE THREAD

**Issue by primerproyecto** [primerproyecto/ahora-puedo-ver#2]
Los tamaños que me has pasado de las imagenes previas del catálogo son **1920x1280** lo que no está mal. Yo de compresión y de peso las veo más o menos bien. Suelen pesar menos de los 200 salvo las fotos que tienen mucho texto que lógicamente pesan más.

Sugiero que las hagas más anchas de **1400px** (ya es suficiente) y así podemos ganar algo más de espacio.
Qué me dices ?

**Comment by nikitanipone** [comment]
Ciao belloooooooo

**Comment by nikitanipone** [comment]
estoy trabajando con imágenes pequeñas y las paso a un formato grande, las tengo que escalar mucho, por lo que se pierde calidad.

Estoy esperando que Antonio me pase las imágenes arregladas así las podré trabajar con mejor calidad…también pesaran mas!!
Sigo editando el catalogo…pero definitivamente irá por ahí la linea….lo que te envié ayer…en cuanto tenga mas resueltas…te envió aunque ya sabes que no son las buenas!

besosssss

**Comment by primerproyecto** [comment]
Ok ....si pudieras decirle a él entonces que te las pasara en formato png supongo que no le importará mucho.

**Comment by nikitanipone** [comment]
porque? no será mejor que yo las convierta en png una vez editadas?

**Comment by nikitanipone** [comment]
te envío 3 mas por correo y sigo trabajando!

**Comment by primerproyecto** [comment]
No ...lo que quieres hacer tu lo puedo hacer yo. Lo suyo sería que...una vez este la foto editada en photoshop, en lugar de exportarlo solo a jpg, hacerlo también a png.
Yo creo que es mejor que te las pase en png ...pregúntaselo. 

Explicarte el porque ...sería dificil ...es una tegnoclogía llamado sprite de compass. Un lío de explicar

**Comment by nikitanipone** [comment]
Tuñonon…no lo acabo de entender….el que yo las edite en photoshop y las pase a png SI. pero….tener los archivos desde antonio directamente en png, no lo entiendo….entre otras cosas porque esos archivos pasan por mi, si o si!

**Comment by nikitanipone** [comment]
te paso mas fotos por el correo…el catalogo va creciendooo

**Comment by primerproyecto** [comment]
ok ..olvídate del png entonces.
Por cierto ...utiliza esto del issue para mensajes turron. No por ejemplo para decirme que me mandas un mail. :-)
