### ISSUE TITLE
paleta de colores

### ISSUE THREAD

**Issue by nikitanipone** [primerproyecto/ahora-puedo-ver#7]
https://coolors.co/app/101912-4f0f2b-c9b39f-e2cbc3-fff6db

**Comment by primerproyecto** [comment]
ok. perfecto. Ya he añadido unos cuantos cambios de color. Echale un vistazo a la página actual http://primerproyecto.github.io/ahora-puedo-ver/

**Comment by nikitanipone** [comment]
Ciao belloo!!!

Your work it´s so cool THANK YOU!!!

Vamos con detalles……

1- me encanta el tono y detalle de los botones iconos…Flecha siguiente, cuando pinchas sobre cada imagen, Creo que es un morado sobre fondo transparente. Usaría esa linea como laitmotiv.

Por partes….

Cabecera: ¿Podemos utilizar esa misma linea? Transparente o blanco o carne con opacidad, pero con las letras en morado como estas usando en los iconos lupa (tal cual es perfecto)cuando pinchas sobre cada imagen…creo que es elegantísimo y queda redondo!!!

Carrusel: La linea tono piel que has puesto es elegantísima, me funciona y también funcionaría en el morado que estas utilizando, pero así de fino!!! YES!!

Fondo galería de imágenes: Cambiaría el rosita por blanco, se ven mas las imágenes, cuando pinchas sobre cada una y se ve la foto en grande…también blanco de fondo. (limpio, jejejej)

Formulario: Fondo de color (PERFECTO!) cambiaría el tono de los textos y los encuadres en negro de la cajita de LISTO y COPIA DE VENTA …… por el tono morado que estamos eligiendo!

Sigo sin ver el logo y el titulo se queda en una esquina!

¿No crees que será mejor ponerlo como imagen para que no de lugar a movimiento dependiendo del ordenador?

Items:

Colección
Visita el Atelier
Camille Hanson
Catalogo en pdf
Enlace a nuestra web, facebook, newslwtter etc…

Paleta de color para el texto gris del prólogo y demás:

https://coolors.co/app/230c19-444444-c19c81-f9f7f8-ffffff

**Comment by nikitanipone** [comment]
https://coolors.co/app/230c19-444444-c9b39f-4f0f2a-ffffff

Paleta de colores que recoge todos los tonos a utilizar!!

Blancos fondos, excepto el de formulario que es la linea 3 de nuestra paleta!

Todos los textos e iconos, en color caja 1 de nuestra paleta

Excepto:

Copia de Venta colección Navidad Nikita Nipone
Listo

Que lo que llevarían morado sería la caja, texto en blanco.

**Comment by nikitanipone** [comment]
Sigo viendo la imagen principal SUPER GRANDE! y el logo…un poco desenfocado!….los ITEM botones, pueden estar alineados a la derecha?

Texto que pone NIKITA NIPONE en medio…quitar.

GRACIAS JUAN!

**Comment by nikitanipone** [comment]
Camille Hanson ha trabajado extensamente como bailarina, coreógrafa y
maestra; se ha producido un flujo constante de trabajos aclamados por la
crítica. Se concentra en producciones escénicas y trabajos site-specific que
generan ambientes evocadores. Está particularmente interesada en en la 
danza y la imagen como medios para transmitir experiencias y plantear 
cuestiones cerca de la superviviencia en tiempos de cambio social y 
medioambiental.
                                                                                                                                                   www.camillehanson.com
