### ISSUE TITLE
precios

### ISSUE THREAD

**Issue by nikitanipone** [primerproyecto/ahora-puedo-ver#9]
2 - Chaqueta a medida….consultar precio
3 - Vestido verde tul……..75€
4 - Jersey bicolor punto…55€
5 - Vestido blanco&negro sport….55e
6 - Jersey geométrico tricolor…….60€
7 - Vestido verde tul……..75€
      Camiseta frambuesa…50e / Legging satén elástico burdeos…30e
8 - Acrílicos y Acuarelas NIKITA NIPONE….a partir de 40€
9 - Abrigo rojo&negro……..85€
10 - Camiseta con tul rayas….50€ / Pantalón pana…..60€
11 -Abrigo rojo&negro……..85€
12 - Pantalón japonés….70e / Camiseta blanco&negro sport…50€
       Legging blanco&negro…20e / Camiseta sport….20e / Chaqueta larga punto 60€
13 - Legging blanco&negro…20e / Camiseta sport….20e / Chaqueta larga punto 60€
14 - Chaqueta a medida….consultar precio
         Pantalón japonés….70e
15 - Camiseta con tul rayas….50€ / Pantalón pana…..60€
        Camiseta negra tul………55€ / Falda pana roja….60€
16 - Camiseta negra tul………55€ / Falda pana roja….60€
17 - Camisa roja gasa………55€
18 - Vestido punto rayas…….60€ / Falda interior tul….65€
19 - Acrílicos y Acuarelas NIKITA NIPONE….a partir de 40€
20 - Camiseta sport naranja…..35€ / Pantalón pana…..60€
21 - Vestido punto rayas…….60€ / Falda interior tul….65€
22 - Vestido cuello alto punto morado….55e /  Legging satén elástico burdeos…30e /
        Rebeca…..45€
23 - Vestido cuello alto punto morado….55e /  Legging satén elástico burdeos…30e
        Jersey algodón rayas…..30€ /  Legging satén elástico burdeos…30e
24 - Jersey cuello alto lentejuelas……55€ / Legging satén elástico burdeos…30e

**Comment by primerproyecto** [comment]
agregados
